### ISSUE TITLE
New Swift XCode 8 app can't see sdk

### ISSUE THREAD

**Issue by Jasonbit** [AppLovin/AppLovin-iOS-SDK-Demo#10]
I downloaded the sdk zip, added the .a and headers via the instructions on the support part of the main AppLovin site. I can't get a new XCode 8 project to see ALSdk so i can use it in the AppDelegate.

I did download the demo app and that seems to work, so I'm just looking for what's different between a new project and the demo. I think the readme should be updated, since technically, it doesn't work for new projects.

**Comment by thomasmso** [comment]
Hi Jason,

We've recently released our [iOS SDK 3.5.0](https://www.applovin.com/integration#iosIntegration) as a first-class framework with detailed instructions for migrating from old old integration method if needed. If you're integrating our SDK anew, you can expose `ALSdk` to your classes by using the statements `#import <AppLovinSDK/AppLovinSDK.h>` or `@import AppLovinSDK;` if you're using modules.

**Comment by monish152** [comment]
Hi But there is no clear documentation to add applovin in old swift codes. Can you please help
