### ISSUE TITLE
createproblem to run time

### ISSUE THREAD

**Issue by PJRadadiya** [AppLovin/AppLovin-iOS-SDK-Demo#9]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_ALAdSize", referenced from:
      objc-class-ref in ALDemoInterstitialManualLoadingViewController.o
  "_OBJC_CLASS_$_ALIncentivizedInterstitialAd", referenced from:
      objc-class-ref in ALDemoRewardedVideosViewController.o
  "_OBJC_CLASS_$_ALInterstitialAd", referenced from:
      objc-class-ref in ALDemoInterstitialSingleInstanceViewController.o
      objc-class-ref in ALDemoInterstitialSharerdInstanceViewController.o
      objc-class-ref in ALDemoInterstitialManualLoadingViewController.o
  "_OBJC_CLASS_$_ALNativeAd", referenced from:
      objc-class-ref in ALCarouselView.o
     (maybe you meant: _OBJC_CLASS_$_ALNativeAdVideoView, _OBJC_CLASS_$_ALNativeAdVideoPlayer )
  "_OBJC_CLASS_$_ALSdk", referenced from:
      objc-class-ref in ALDemoAppDelegate.o
      objc-class-ref in ALCarouselCardView.o
      objc-class-ref in ALDemoInterstitialSingleInstanceViewController.o
      objc-class-ref in ALDemoNativeAdProgrammaticViewController.o
      objc-class-ref in ALDemoRootViewController.o
      objc-class-ref in ALCarouselView.o
      objc-class-ref in ALCarouselMediaView.o

**Comment by thomasmso** [comment]
Hi, are you sure you also added the **libAppLovinSdk.a** file to your target and not just the header files?

**Comment by PJRadadiya** [comment]
yes,but not my app your example project say this error.

**Comment by PJRadadiya** [comment]
I am say your example project Error.

**Comment by thomasmso** [comment]
The demo apps do not come bundled with our SDK. You have to download the latest iOS SDK [here](https://www.applovin.com/integration#iosIntegration) and add your SDK key to the `Info.plist` file.

**Comment by PJRadadiya** [comment]
ok thanks

p.j.radadiya

**Comment by thomasmso** [comment]
No problem!
